- name: Create RoboShop Config in Nginx
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Nginx
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Explicitly specifying positional matched groups in replacement
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    daemon_reload: true
    enabled: true
    