- name: copy {{ component }} service file
  ansible.builtin.copy: 
    src: "{{ component }}.serice"
    dest: /etc/systemd/system/{{ component }}.service

- name: start {{ component }} service file
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes
