
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent


- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes



echo -e "${color} Enabling Nginx ${nocolor}"
systemctl enable nginx &>> ${log_file}
systemctl start nginx &>> ${log_file}
status_check $?

echo -e "${color} Restart nginx ${nocolor}"
systemctl restart nginx &>> ${log_file}
status_check $?